global:
  scrape_interval: 5s # Как часто Prometheus будет ходить в наше приложение и забирать метрики

scrape_configs: # Какие приложения мы отслеживаем
  - job_name: "litestar" # собственное название джобы
    metrics_path: /metrics # Адрес приложения, куда будет ходить prometheus за метриками
    static_configs:
      - targets: ["backend:8080"] # Тк мы находимся в одной докер сети, то здесь указываем название контейнера.
      # Иначе бы указывали IP сервера, где находится приложение
